# Generated by Django 2.2.10 on 2021-12-15 17:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(default=datetime.date.today)),
                ('end_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('type', models.SmallIntegerField(choices=[(1, 'text box'), (2, 'single choice'), (3, 'multiple choice')], default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Survey')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('toquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Question')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('tooption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Option')),
            ],
        ),
    ]
