# Generated by Django 2.2.10 on 2021-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211216_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='option',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='option',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
