# Generated by Django 2.2.10 on 2021-12-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211217_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantId', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tooption',
        ),
        migrations.AddField(
            model_name='answer',
            name='questionId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Participant'),
            preserve_default=False,
        ),
    ]
