# Generated by Django 2.2.10 on 2021-12-20 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211220_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participantId',
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
